# Generated by Django 5.2.11 on 2026-02-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image',
            field=models.ImageField(default='pet_images/default.jpg', upload_to='pet_images/'),
        ),
    ]
