# Generated by Django 5.2.11 on 2026-04-11 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='address',
            new_name='ADDRESS',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='prodect',
            new_name='PRODUCT',
        ),
    ]
