# Generated by Django 5.2.11 on 2026-04-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_address_orders_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
